### PR TITLE
6.5 Add stripe gem and start the basic and test payment configuration

### PR DESCRIPTION
**Pull request by nelantone**

### CODE REVIEW

**Comment by wazery** [comment]
I will just add my approval 👍  on this, and not merge, I will leave that for you @nelantone :)

**Comment by wazery** [comment]
How I can say that you are very professional in your workflow? You use PRs (Pull Requests), your Git history is just perfect, you create separate branches for each feature, your code is beautiful and matching the best practices. How can I describe my happiness with your work 😄.

**Comment by nelantone** [comment]
@wazery don't make me red, haha! Thanks dude! I'm just using what I learnt the year working for companies as ruby intern and the 8 months as Jr. RoR Dev.
I do my best to keep in order (at least my code ^^).
It's a pleasure :)
Thanks for your compliments!
I hope in the future I will create some gems like you!
This is so cool!
T

**Comment by nelantone** [comment]
Then I :ship: it! :+1: .
Thanks :smile:

**Pull request merged**
